networks:
  app-network:
    driver: bridge

services:

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - app-network
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=4096M
    volumes:
      - ./scripts:/scripts
      - ./sparkdata:/sparkdata
      - cassandra-node:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 6

  spark:
    container_name: spark
    image: jupyter/all-spark-notebook:spark-3.5.0
    env_file: .env
    command: >
      sh -c '
      pip install --upgrade pip &&
      pip install -r /app/requirements.txt &&
      start-notebook.sh --NotebookApp.token="" --NotebookApp.password=""'
    ports:
      - 8888:8888 # Jupyter web interface
      - 4040:4040 # Spark UI
    networks:
      - app-network
    working_dir: /app
    depends_on:
      - cassandra
    volumes:
      - ./:/app

volumes:
  cassandra-node:
